version: "3.9"

services:
  app:
    build: .
    container_name: linguada-app
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - RELOAD=false
      - LOG_LEVEL=info

      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      # - REDIS_URL=redis://redis:6379/0

      - AUDIO_SAMPLE_RATE=16000
      - AUDIO_BITRATE=8k
      - AUDIO_CHANNELS=1
      - MAX_AUDIO_DURATION=600
      - MAX_CONCURRENT_DOWNLOADS=3

    depends_on:
      - redis

    volumes:
      - whisper_cache:/root/.cache/whisper

    networks:
      - edtech-net

  redis:
    image: redis:7-alpine
    container_name: linguada-redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data
    networks:
      - edtech-net

volumes:
  redis_data:
  whisper_cache:

networks:
  edtech-net:
    driver: bridge
